id: P010693
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19341
  title: གསུང་འབུམ། རིག་འཛིན་གར་གི་དབང་ཕྱུག
  author: ''
  volumes:
    2c5de3dec2b2401a976edebadbadaa40:
      image_group_id: I8LS19343
      title: ''
      volume_number: 1
      total_pages: 598
      base_file: v001.txt
