id: ICA69FF71
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T08:28:44+00:00'
last_modified: '2022-06-08T16:51:06.056713+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19341
  title: གསུང་འབུམ། རིག་འཛིན་གར་གི་དབང་ཕྱུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3B51:
      image_group_id: I8LS19343
      title: ''
      total_pages: 598
      order: 1
      base_file: 3B51.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
